services:
  - type: web
    name: basketball-team-line-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
